### ISSUE TITLE
Bug: TypeError: web3_eth_accounts_1.default is not a constructor

### ISSUE THREAD

**Issue by sansan88** [project-owlly/cloud#100]
TypeError: web3_eth_accounts_1.default is not a constructor
    at checkSignature (/workspace/lib/scheduler/mailbox/utils/parser.utils.js:141:22)
    at Object.getSignatures (/workspace/lib/scheduler/mailbox/utils/parser.utils.js:42:30)
    at Object.readMailboxPdfs (/workspace/lib/scheduler/mailbox/utils/mailbox.utils.js:35:43)
    at process._tickCallback (internal/process/next_tick.js:68:7)

**Comment by sansan88** [comment]
https://github.com/ethereum/web3.js/issues/3292

https://github.com/ethereum/web3.js/pull/3732
