### ISSUE TITLE
feat: Missing storage permission

### ISSUE THREAD

**Issue by sansan88** [project-owlly/cloud#77]
`generatePDF
Unhandled error { Error: The caller does not have permission
    at Gaxios._request (/workspace/node_modules/gaxios/build/src/gaxios.js:89:23)
    at process._tickCallback (internal/process/next_tick.js:68:7) name: 'SigningError' } `

![grafik](https://user-images.githubusercontent.com/2372120/98419793-1847d780-2086-11eb-8501-724a790f3ea7.png)

**Comment by sansan88** [comment]
fixed by adding firebase storage admin to service account.. 
not sure this is the best way
